#!/usr/bin/env node

const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function writeLine(obj) {
  fs.writeSync(1, `${JSON.stringify(obj)}\n`);
}

function readStdin() {
  return new Promise((resolve) => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => { data += chunk; });
    process.stdin.on('end', () => resolve(data));
  });
}

(async function main() {
  const args = process.argv.slice(2);
  if (args.join(' ') === '--help') {
    process.stdout.write(`Codex CLI

Commands:
  exec         Run Codex non-interactively
  review       Run a code review non-interactively
  login        Manage login
  logout       Remove stored authentication credentials
  mcp          Manage external MCP servers for Codex
  plugin       Manage Codex plugins
  resume       Resume a previous interactive session
  features     Inspect feature flags

Options:
  -h, --help   Print help
`);
    return;
  }
  if (args.join(' ') === 'mcp --help') {
    process.stdout.write(`Manage external MCP servers for Codex

Commands:
  list
  get
  add
  remove

Options:
  -h, --help   Print help
`);
    return;
  }
  if (args[0] !== 'exec') {
    process.stdout.write(`Codex native start ${args.join(' ')}\n`);
    await sleep(120);
    process.stdout.write(`Codex native end ${args.join(' ')}\n`);
    return;
  }
  // agent-web can place `resume` after other `codex exec` options (e.g. --json, -s).
  const isResume = args[0] === 'exec' && args.includes('resume');
  const threadId = (() => {
    if (!isResume) return `mock-${crypto.randomUUID()}`;
    for (let i = args.length - 1; i >= 2; i--) {
      const arg = args[i];
      if (arg === '-' || String(arg).startsWith('-')) continue;
      return arg;
    }
    return `mock-${crypto.randomUUID()}`;
  })();
  const input = (await readStdin()).trim();
  const imageCount = args.filter((arg) => arg === '--image').length;
  const statePath = path.join(os.tmpdir(), `cc-web-mock-codex-${threadId}.json`);
  let state = {};
  try {
    state = JSON.parse(fs.readFileSync(statePath, 'utf8'));
  } catch {}

  writeLine({ type: 'thread.started', thread_id: threadId });
  writeLine({ type: 'turn.started' });

  if (/pwd/i.test(input)) {
    writeLine({
      type: 'item.started',
      item: {
        id: 'item_cmd',
        type: 'command_execution',
        command: '/bin/bash -lc pwd',
        aggregated_output: '',
        exit_code: null,
        status: 'in_progress',
      },
    });
    writeLine({
      type: 'item.completed',
      item: {
        id: 'item_cmd',
        type: 'command_execution',
        command: '/bin/bash -lc pwd',
        aggregated_output: '/tmp/mock-codex\n',
        exit_code: 0,
        status: 'completed',
      },
    });
  }

  if (input === '/compact') {
    state.compacted = true;
    fs.writeFileSync(statePath, JSON.stringify(state));
  }

  const isInitPrompt = input === '/init' || input.includes('You are running agent-web\'s /init for a Codex session.');

  if (isInitPrompt) {
    const agentsPath = path.join(process.cwd(), 'AGENTS.md');
    fs.writeFileSync(agentsPath, '# AGENTS.md\n\nGenerated by mock Codex /init.\n');
  }

  if (input === 'trigger codex context limit' && !state.compacted) {
    state.compacted = true;
    fs.writeFileSync(statePath, JSON.stringify(state));
    writeLine({
      type: 'turn.failed',
      error: { message: 'Context window exceeded. Please use /compact and retry.' },
    });
    // fs.writeSync writes directly to the fd — no stream buffer to flush.
    process.exitCode = 1;
    return;
  }

  const responseText = input === '/compact'
    ? 'Codex compact finished.'
    : isInitPrompt
      ? 'Codex init finished.'
    : `Codex mock handled (${imageCount} image): ${input}`;

  writeLine({
    type: 'item.completed',
    item: {
      id: 'item_msg',
      type: 'agent_message',
      text: responseText,
    },
  });

  if (input === 'trigger codex context limit' && state.compacted) {
    try { fs.unlinkSync(statePath); } catch {}
  }

  writeLine({
    type: 'turn.completed',
    usage: { input_tokens: 10, cached_input_tokens: 2, output_tokens: 5 },
  });

  if (input.includes('slow logical completion first')) {
    await sleep(2500);
  }
})();
